source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

pod 'AFNetworking', '~> 2.5.1'
pod 'ASIHTTPRequest', '~> 1.8.2'
pod 'NSLogger', '~> 1.5.1'
pod 'SDWebImage', '~> 3.7.1'
pod 'MWPhotoBrowser', '~> 1.4.1'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'ViewDeck', '~> 2.3.1'
pod 'VPImageCropper', '~> 0.0.4'
pod 'IGDigest', '~> 1.1.2'
pod 'IQKeyboardManager', '~> 3.2.1.1'
pod 'SVPullToRefresh', '~> 0.4.1'
pod 'FXLabel', '~> 1.5.8'
pod 'NSData+Base64', '~> 1.0.0'
pod 'UITextView+Placeholder', '~> 1.0.9'
pod 'ASProgressPopUpView', '~> 0.8'

